// Copyright the ImgEdge contributors.
// SPDX-License-Identifier: Apache-2.0
/**
 * Pure, environment-agnostic core of the in-browser "Fast" classifier.
 *
 * These functions mirror imgedge.inat.inat_filter (`prep_input` / `postprocess`)
 * so the browser path stays in numeric parity with the Python pipeline. They
 * take and return plain typed arrays / numbers -- no DOM, canvas, or ONNX
 * Runtime -- so they run unchanged in a Node test and in the extension's
 * offscreen document (which owns image decoding + the ORT session, wired in a
 * later phase). Constants live in inat_web.json (generated by
 * tools/export_inat_web.py).
 */

/**
 * Convert RGBA pixel bytes (as produced by canvas `getImageData`) for a
 * width*height image into the model's NHWC float32 input data. Mirrors
 * `prep_input` for a float32 input: `value / divisor + offset` over the RGB
 * channels, dropping alpha (uint8 [0,255] -> Inception-style [-1, 1]).
 *
 * @param {Uint8ClampedArray|Uint8Array|number[]} rgba - length width*height*4
 * @param {number} width
 * @param {number} height
 * @param {{divisor?: number, offset?: number}} [opts]
 * @returns {Float32Array} length width*height*3, NHWC order
 */
export function toModelInput(rgba, width, height, { divisor = 127.5, offset = -1.0 } = {}) {
  const out = new Float32Array(width * height * 3);
  let j = 0;
  for (let i = 0; i + 3 < rgba.length; i += 4) {
    out[j++] = rgba[i] / divisor + offset;
    out[j++] = rgba[i + 1] / divisor + offset;
    out[j++] = rgba[i + 2] / divisor + offset;
  }
  return out;
}

/**
 * P(image depicts the target taxon) in [0, 1]: the model's non-negative,
 * sum-normalized probability mass over the target leaf indices. Mirrors
 * `postprocess` -- clip negatives to 0, normalize by the total, sum the mask.
 *
 * @param {Float32Array|number[]} output - the model's raw output vector
 * @param {number[]} indices - target (e.g. Arachnida) leaf indices
 * @returns {number}
 */
export function targetScore(output, indices) {
  let total = 0;
  for (let i = 0; i < output.length; i++) {
    if (output[i] > 0) total += output[i];
  }
  if (total <= 0) return 0;
  let mass = 0;
  for (let k = 0; k < indices.length; k++) {
    const idx = indices[k];
    if (idx >= 0 && idx < output.length && output[idx] > 0) mass += output[idx];
  }
  return mass / total;
}

/**
 * Verdict for iNat-only Fast mode: block when the score meets the threshold
 * (matches the ensemble's `>=` comparison).
 *
 * @param {number} score
 * @param {number} threshold
 * @returns {boolean}
 */
export function isBlocked(score, threshold) {
  return score >= threshold;
}
