# Copyright the ImgEdge contributors.
# SPDX-License-Identifier: Apache-2.0
name: CodSpeed

on:
  push:
    branches: [main]
  pull_request:
  # Allows CodSpeed to trigger backtest performance analysis to generate
  # initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

concurrency:
  group: codspeed-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -e . "pytest-codspeed==5.0.3"
      - name: Run benchmarks
        uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          mode: simulation
          run: pytest benchmark/ --codspeed
